version: '3.9'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "npm i && npm run build && npm run dev"
    networks:
      - backend-network
    restart: unless-stopped

  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
